### ISSUE TITLE
TypeError: str is undefined in  BeforeInputEventPlugin.js:10

### ISSUE THREAD

**Issue by mathiasconradt** [auth0-community/auth0-editprofile-widget#19]
I get `TypeError: str is undefined` error in `BeforeInputEventPlugin.js:10`

<img width="890" alt="screen shot 2019-02-26 at 9 27 19 am" src="https://user-images.githubusercontent.com/295122/53397962-c3932480-39a8-11e9-9b7f-86f976ddacb2.png">

<img width="1053" alt="screen shot 2019-02-26 at 9 27 08 am" src="https://user-images.githubusercontent.com/295122/53397964-c68e1500-39a8-11e9-9d0f-d6b0b8847bc2.png">

On another note: 
The built `auth0-editprofile-widget.js` file contains absolute local paths, like: `/Users/germanlena/Projects/`. Not sure if this is supposed to be in there.

**Comment by beardaway** [comment]
Hey there!

Can you use the issue template we provide so it is potentially easier for someone reviewing this to clearly understand what way you took and what happened along? Thank you a lot! Feel free to re-open it once you have it!

**Comment by mathiasconradt** [comment]
@beardaway Sorry, original post is adjusted.

**Comment by mathiasconradt** [comment]
@beardaway I cannot re-open the issue b/c I didn't close it. At least I see no option. Description is adjusted, please re-open.
